steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/hexdocs-build:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/hexdocs:latest']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hexdocs-build:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hexdocs-build:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/hexdocs-build:latest'
  - '--target'
  - 'build'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hexdocs:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hexdocs:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/hexdocs:latest'
  - '--target'
  - 'app'
  - '.'

images:
- 'gcr.io/$PROJECT_ID/hexdocs-build:latest'
- 'gcr.io/$PROJECT_ID/hexdocs:latest'
- 'gcr.io/$PROJECT_ID/hexdocs-build:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/hexdocs:$SHORT_SHA'
